apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 978793441425.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 978793441425.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 986d6319
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
